# Generated by Django 6.0.3 on 2026-04-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
